# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellPhoneNum',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
