# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170429_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellPhoneNum',
            field=models.CharField(max_length=11),
        ),
    ]
