# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170429_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('can_view', 'Can see teacher'), ('can_add', 'Can add teacher'), ('can_edit', 'Can edit teacher'), ('can_delete', 'Can delete teacher'))},
        ),
    ]
