# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170430_1223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
