# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_thread', models.TextField(blank=True, null=True)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_url', models.TextField(blank=True, null=True)),
                ('news_time', models.TextField(blank=True, null=True)),
                ('news_from', models.TextField(blank=True, null=True)),
                ('from_url', models.TextField(blank=True, null=True)),
                ('news_body', models.TextField(blank=True, null=True)),
                ('dele', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
